name: flutter_go_router_workspace
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.2

  # Routing
  go_router: ^11.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 

  # Generater
  build_runner: ^2.4.6
  go_router_builder: ^2.3.3

flutter:
  uses-material-design: true